worker_heartbeat_timeout: 300000

logging:
  level: info

services:
  - module: /usr/lib/parsoid/src/lib/index.js
    entrypoint: apiServiceWorker
    conf:
      mwApis:
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
        - uri: 'https://<%= wiki %>.miraheze.org/w/api.php'
          domain: '<%= wiki %>.miraheze.org'
<%- else -%>
        - uri: 'https://<%= value %>/w/api.php'
          domain: '<%= value %>'
<%- end -%>
<%- end -%>
      loadWMF: false
      debug: false
      usePHPPreProcessor: true
      useSelser: true
      linting: true
      linterSendAPI: false
